# Generated by Django 3.1.7 on 2021-03-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210328_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_department',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
