# Generated by Django 3.1.7 on 2021-03-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210320_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='price',
        ),
    ]
