# Generated by Django 3.1.7 on 2021-03-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210325_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
