# Generated by Django 3.1.7 on 2021-03-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(default=1, max_length=254),
        ),
    ]
